name: RSS to Kindle

on:
  schedule:
    # 每天北京时间早上9点运行 (UTC时间23:00)
    - cron: '0 11 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  convert-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml feedparser requests ebooklib pillow beautifulsoup4 readability-lxml lxml
        # 如果有 requirements.txt 则使用
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
    
    - name: Create email config from secrets
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        KINDLE_EMAIL: ${{ secrets.KINDLE_EMAIL }}
      run: |
        cat > email_config.yaml << EOF
        smtp_server: "$SMTP_SERVER"
        smtp_port: $SMTP_PORT
        sender_email: "$SENDER_EMAIL"
        sender_password: "$SENDER_PASSWORD"
        kindle_email: "$KINDLE_EMAIL"
        subject: "RSS Feed - $(date +%Y-%m-%d)"
        body: "您订阅的RSS内容 - $(date +%Y-%m-%d)"
        EOF
    
    - name: Generate EPUB and send to Kindle
      env:
        # RSS配置 - 使用Repository Variable或Secret
        CONFIG_YAML: ${{ vars.CONFIG_YAML || secrets.CONFIG_YAML }}
      run: |
        python rss_and_send.py
    
    - name: Upload EPUB as artifact (backup)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rss-epub-${{ github.run_number }}
        path: rss_feed_*.epub
        retention-days: 7
    
    - name: Clean up old EPUBs
      run: |
        # 保留最新的3个EPUB文件，删除其他
        ls -t rss_feed_*.epub 2>/dev/null | tail -n +4 | xargs -r rm -f
